br_b3_cotacoes.dicionario
basedosdados/staging-queries-basedosdados pull request #36
Opened 2023-06-07 14:46 UTC by tricktx

2023-06-13 18:38 UTC, laura-l-amaral requested changes
o dicionario está duplicado e com as colunas de chave e valor invertidas

<img width="446" alt="image" src="https://github.com/basedosdados/staging-queries-basedosdados/assets/100051996/16dc6c93-031a-4add-b02f-93660e575289">

2023-06-13 18:42 UTC, tricktx commented
@laura-l-amaral 
Havia duas tabelas no storage, vacilo meu.
Irei consertar.

2023-06-16 15:14 UTC, arthurfg approved these changes

2023-06-16 15:14 UTC, arthurfg approved these changes

2023-06-16 16:43 UTC, laura-l-amaral approved these changes

2023-06-16 16:44 UTC, merged